apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: istio-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: istio-rollout
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: istio-rollout
    spec:
      containers:
        - name: istio-rollout
          image: argoproj/rollouts-demo:yellow
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: istio-rollout
      previewService: istio-rollout-canary
    # canary:
    #   canaryService: istio-rollout-canary
    # trafficRouting:
    #   istio:
    #     virtualServices:
    #       - name: istio-rollout-vsvc
    #     destinationRule:
    #       name: rollout-destrule # required
    #       canarySubsetName: canary # required
    #       stableSubsetName: stable # required
    # steps:
    #   - setWeight: 20
    #   - pause: {}
    #   - setWeight: 40
    #   - pause: { duration: 10 }
    #   - setWeight: 60
    #   - pause: {}
    #   - setWeight: 80
    #   - pause: { duration: 10 }
