apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - "*"
  http:
    - name: primary
      match:
        - header:
            host: "istio-subset.localhost"
      route:
        - destination:
            host: istio-rollout
    - name: canary
      match:
        - header:
            host: "istio-subset.canary.localhost"
      route:
        - destination:
            host: istio-rollout-canary
            # subset: stable # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
        #   weight: 100
        # - destination:
        #     host: istio-rollout-canary
        #     subset: canary # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
        #   weight: 0
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: istio-rollout-vsvc-canary
# spec:
#   gateways:
#     - istio-rollout-gateway-canary
#   hosts:
#     - "*"
#   http:
#     - name: canary
#       route:
#         - destination:
#             host: istio-rollout-canary
# subset: canary # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
