apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - "*"
  http:
    - name: primary
      route:
        - destination:
            host: istio-rollout
            subset: stable # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc-canary
spec:
  gateways:
    - istio-rollout-gateway-canary
  hosts:
    - "*"
  http:
    - name: canary
      route:
        - destination:
            host: istio-rollout-canary
            subset: canary # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
