apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
    - istio-rollout-gateway
  http:
    - name: primary
      match:
        - uri:
            prefix: "istio-subset.localhost"
      route:
        - destination:
            host: istio-rollout
            subset: stable # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    - name: canary
      match:
        - uri:
            prefix: "istio-subset.canary.localhost"
      route:
        - destination:
            host: istio-rollout
            subset: canary # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
